### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by Ritvik-UX**
Added HTML, CSS, JS Image

### CODE REVIEW

**Comment by Subhradeep10** [comment]
@Ritvik-UX Can you share the images of your code

**Comment by Subhradeep10** [comment]
@Ritvik-UX Can you please share the screenshot of readme after changes

**Comment by Subhradeep10** [comment]
@Ritvik-UX Can you place them in center?

**Comment by Ritvik-UX** [comment]
> @Ritvik-UX Can you place them in center?
@Subhradeep10  Done :D

**Comment by Subhradeep10** [comment]
@Ritvik-UX Great

**Pull request merged**
