### PR TITLE
Update index.html

### PR DESCRIPTION
**Pull request by kshitijmishra27**
The added description  below Health is Wealth heading 
Added description for a leg workout, chest workout, back workout, arm workout

### CODE REVIEW

**Comment by TusharKesarwani** [comment]
Please first create an issue then make PR

**Comment by kshitijmishra27** [comment]
@TusharKesarwani  already created the issue 2 days ago and talked to the admin

**Comment by TusharKesarwani** [comment]
Ok,
Please mention issue number when you are making PR from next time @kshitijmishra27

**Comment by Subhradeep10** [comment]
@kshitijmishra27 Resolve the conflicts

**Comment by kshitijmishra27** [comment]
resolved the conflits 😄

**Pull request merged**
