### PR TITLE
changed the register section interface and added effect to the button

### PR DESCRIPTION
**Pull request by Harsh3363**
My PR fix issue #40 
Made changes to the register section 

Screenshot (94)

### CODE REVIEW

**Review by Subhradeep10 — CHANGES_REQUESTED** [review]
Can you add something more in the right side, cause it's looking very much black.
You can add a Google map..(my suggestion) else you can do something else... whatever your choice

**Comment by Harsh3363** [comment]
> Can you add something more in the right side, cause it's looking very much black. You can add a Google map..(my suggestion) else you can do something else... whatever your choice

yeah i will make the changes

**Comment by Subhradeep10** [comment]
@Harsh3363 Any update?

**Comment by Harsh3363** [comment]
> @Harsh3363 Any update?
> 

I'm working on this will finish by tomorrow 
Sorry for the delay

**Comment by Subhradeep10** [comment]
PR is closed due to inactivity

**Pull request closed without merging**
