### PR TITLE
improved the cards ui on home page

### PR DESCRIPTION
**Pull request by vaibhavsharma1234**
https://github.com/Subhradeep10/Fitnezz/issues/84
this is the issue

### CODE REVIEW

**Comment by Subhradeep10** [comment]
@vaibhavsharma1234 Resolve the merge conflicts

**Comment by vaibhavsharma1234** [comment]
review this now

**Comment by Subhradeep10** [comment]
@vaibhavsharma1234 Again

**Comment by vaibhavsharma1234** [comment]
why it shows conflict again and again is it something i  am doing wrong

**Comment by vaibhavsharma1234** [comment]
i hope this gets merged before any other branch merge otherwise i think it will again show conflicts

**Pull request merged**
