### PR TITLE
Multiple Color Issues, Form in Footer --Fixed

### PR DESCRIPTION
**Pull request by Ritvik-UX**

### CODE REVIEW

**Comment by Ritvik-UX** [comment]
- Images allotted border-radius
- form in footer
- Single Color = Purple

Added Sticky Header in line 65 of CSS in Comments
Add the code in comments in .header class if you need sticky header, else remove it.

:D

**Review by Subhradeep10 — CHANGES_REQUESTED** [review]
Kindly Share the screenshot of your Result

**Comment by Subhradeep10** [comment]
@Ritvik-UX You did a Great Work 🚀

**Comment by Ritvik-UX** [comment]
> @Ritvik-UX You did a Great Work 🚀

Thank You So Much :D

**Pull request merged**
