### PR TITLE
Fixed Bug, Footer and Form is Responsive for screen sizes above 225px (i.e, almost all devices :D)

### PR DESCRIPTION
**Pull request by Ritvik-UX**

### CODE REVIEW

**Comment by Subhradeep10** [comment]
@Ritvik-UX Whenever You doing any task, First kindly say it at the issue, Then I will assigned it to you
And Please share the screenshot , does'nt need to explain in the picture

**Comment by Ritvik-UX** [comment]
> @Ritvik-UX Whenever You doing any task, First kindly say it at the issue, Then I will assigned it to you
> And Please share the screenshot , does'nt need to explain in the picture

Will Take Care Next Time Onwards :D
Screenshots below:
1. 200px
form 200px

2. 300px
form 300px

3. 476px
form 476px

4. 477px onwards
form 477 pixel onwards

**Comment by Subhradeep10** [comment]
@Ritvik-UX Great job 🚀🚀

**Comment by Ritvik-UX** [comment]
> @Ritvik-UX Great job 🚀🚀

Thank You So Much :D

**Pull request merged**
