### PR TITLE
modified the navbar under the branch stickyNav

### PR DESCRIPTION
**Pull request by Cypher1002**
please review it if any issues are there then i will resolve it soon

issue no #97

### CODE REVIEW

**Comment by TusharKesarwani** [comment]
@Cypher1002  Please mention issue number you are resolving

**Comment by Cypher1002** [comment]
> @Cypher1002 Please mention issue number you are resolving

what is the status about my pr can i get some clarification?

**Comment by TusharKesarwani** [comment]
You have to mention #50 
When you are making PR
Next time please mention this correctly

**Comment by Cypher1002** [comment]
I will keep that in mind

**Pull request merged**
