### PR TITLE
new commit

### PR DESCRIPTION
**Pull request by vaibhavsharma1234**
https://github.com/Subhradeep10/Fitnezz/issues/121
ps- i am loving contributing in this project thanks for so many issues

### CODE REVIEW

**Comment by TusharKesarwani** [comment]
Why you have created new files for the join page?
You should change the code of the previous file
This is sufficient
Please do this @vaibhavsharma1234

**Comment by vaibhavsharma1234** [comment]
okay

**Comment by vaibhavsharma1234** [comment]
@TusharKesarwani  its done please merge

**Comment by TusharKesarwani** [comment]
OK, Now its fine @vaibhavsharma1234

**Review by TusharKesarwani — APPROVED** [review]

**Pull request merged**
