### PR TITLE
Improved the Home page

### PR DESCRIPTION
**Pull request by Vanshiii203**
issue #140 
Changed the font size, font family and font weight of the section, also added a gradient transition to the text, and hover effect and transition to join in button and did some basic padding and margin changes.

https://user-images.githubusercontent.com/94471189/184313589-b1583033-4b3c-414e-9926-32059d7c36f2.mp4

### CODE REVIEW

**Comment by Atharv-110** [comment]
Reviewed and ready for the merge!

**Review by Atharv-110 — APPROVED** [review]
Reviewed and ready to merge

**Comment by TusharKesarwani** [comment]
All works fine
Good work @Vanshiii203

**Review by TusharKesarwani — APPROVED** [review]

**Review by Subhradeep10 — COMMENTED** [review]
Great Work

**Pull request merged**
