### PR TITLE
Add a Description of the coaches available to train the users #64

### PR DESCRIPTION
**Pull request by Prahmodh-R**
My Pull Request to issue #64 
I have added the description of 4 coaches. Please let me know if its fine.

image
image

### CODE REVIEW

**Comment by Subhradeep10** [comment]
@Atharv-110 @TusharKesarwani Review his code

**Review by Subhradeep10 — COMMENTED** [review]
@Atharv-110 @TusharKesarwani Review his code

**Comment by Subhradeep10** [comment]
@SachinMittal1766 Review the code

**Comment by TusharKesarwani** [comment]
@Prahmodh-R

**Comment by Prahmodh-R** [comment]
Ok, I'll do that

**Comment by Prahmodh-R** [comment]
@TusharKesarwani I've added the hover option to the card class again, please check it now

**Comment by TusharKesarwani** [comment]
@Prahmodh-R Ok, now it's fine!!

**Comment by Prahmodh-R** [comment]
Glad to hear that. Will my pull request be merged to the master branch of the project now?

**Comment by TusharKesarwani** [comment]
Yeah, it will be merged soon.

**Comment by Subhradeep10** [comment]
@Prahmodh-R Merged

**Comment by Prahmodh-R** [comment]
My Devfolio Username: Prahmodh_Raj
Mail-Id: pramodhr181@gmail.com

**Pull request merged**
