### PR TITLE
Added details near registration form

### PR DESCRIPTION
**Pull request by AnushkaMittal21**
Added address, phone number, and mail id with contact icons.
It's fully responsive as well.

### CODE REVIEW

**Comment by TusharKesarwani** [comment]
Please mention issue number

**Comment by AnushkaMittal21** [comment]
> Please mention issue number

It's 120

**Comment by TusharKesarwani** [comment]
#120 
Tagging issue number is a must when you are making PR
Please take care of this thing next time

**Comment by AnushkaMittal21** [comment]
> #120 Tagging issue number is a must when you are making PR Please take care of this thing next time

Okay

**Comment by Subhradeep10** [comment]
@AnushkaMittal21 Pull the code and then push it, It's have conflicts

**Comment by AnushkaMittal21** [comment]
> @AnushkaMittal21 Pull the code and then push it, It's have conflicts

how should I do that?

**Comment by Subhradeep10** [comment]
@AnushkaMittal21 Do git pull,  and then push it

**Comment by AnushkaMittal21** [comment]
> @AnushkaMittal21 Do git pull, and then push it

I have done that but its showing everything is up to date.

**Pull request closed without merging**
