### PR TITLE
Animations on Scrolling has been added in each cards

### PR DESCRIPTION
**Pull request by Anubhavgupta14**
Animations on Scrolling has been added in each cards.
Issue Solved :- #295 
@TusharKesarwani Kindly Review it.

### CODE REVIEW

**Comment by Anubhavgupta14** [comment]
https://user-images.githubusercontent.com/97956667/192147849-0bde986c-60a5-437c-830d-fd07516382b8.mp4

**Review by TusharKesarwani — APPROVED** [review]

**Comment by Anubhavgupta14** [comment]
@Subhradeep10 Kindly Review this PR, I have updated the code according to new merge code.

**Comment by Subhradeep10** [comment]
@Anubhavgupta14 Resolve conflict

**Comment by Anubhavgupta14** [comment]
@Subhradeep10 I have resolved the conflicts kindly merge it.

**Pull request merged**
