### PR TITLE
Update the designing of the boxes

### PR DESCRIPTION
**Pull request by zugzwang03**
The boxes have been designed with box shadow and necessary highlights, you can check the working here.
https://zugzwang03.github.io/Fitnezz/

### CODE REVIEW

**Review by Subhradeep10 — COMMENTED** [review]
Can you share the screenshot of your changes

**Comment by zugzwang03** [comment]
previously it was :
fit1
After making changes, it is :
fit2

**Comment by zugzwang03** [comment]
Basically the cards get highlighted on hovering around them

**Comment by Subhradeep10** [comment]
@zugzwang03 I have alloted you as a part of SSOC, dont worry

**Comment by zugzwang03** [comment]
Kindly put the "SSOC" tag here along with difficulty level as the SSOC team is kind of strict about tagging the PRs. @TusharKesarwani @Subhradeep10

**Pull request merged**
