### PR TITLE
added the native height and width to the html img tag

### PR DESCRIPTION
**Pull request by Yusuf-gitCollab**
I read a guide and it said to add the native height and width of the images in the  so I did so. I am aware of the aspect ratio 16:9 but I did not exactly understand whether I should add the native dimensions or I should calculate the perfect dimensions. As the guide also said that we need to used the dimensions that are as close as the original dimensions.

### CODE REVIEW

**Comment by Yusuf-gitCollab** [comment]
@Subhradeep10  Can you please tell me how to add images. As I don't know how to. Also can you also tell me how to use emojis in git hub

**Comment by Subhradeep10** [comment]
For images use </img> and for emoji I copy it from online https://emojis.wiki/

**Comment by Yusuf-gitCollab** [comment]
🎨 okay but what about images bro

**Comment by Subhradeep10** [comment]
@Yusuf-gitCollab Edited

**Pull request merged**
