### PR TITLE
UI Improved Caursal has been added and social media links.

### PR DESCRIPTION
**Pull request by Anubhavgupta14**
UI

### CODE REVIEW

**Comment by Anubhavgupta14** [comment]
@TusharKesarwani Please Review my PR. I have resolved my Merge Conflict

**Comment by Anubhavgupta14** [comment]
f
Screenshot 2022-08-08 223911

**Comment by TusharKesarwani** [comment]
Issue no. #56 
Next time please mention the issue number you are fixing.

**Comment by Anubhavgupta14** [comment]
@Subhradeep10 Conflict Resolved

**Pull request merged**
