### PR TITLE
Set the maxlength, added the placeholder and added a dropdown for gender

### PR DESCRIPTION
**Pull request by mundadapurva**
Hey, I've set the maxlength, added the placeholder, added the dropdown for gender, and made a few minor changes in the registration form.

### CODE REVIEW

**Comment by TusharKesarwani** [comment]
Please resolve conflicts

**Comment by TusharKesarwani** [comment]
Mention issue number you are fixing

**Comment by mundadapurva** [comment]
> Mention issue number you are fixing

It's 98

**Comment by mundadapurva** [comment]
> Please resolve conflicts

Could you guide me, please?

**Comment by TusharKesarwani** [comment]
#98 
Tagging issue number is a must when you are making PR
Please take care of this thing next time

**Comment by TusharKesarwani** [comment]
> > Please resolve conflicts
> 
> Could you guide me, please?

It's easy,
You can watch this tutorial https://www.youtube.com/watch?v=nfOxUaA2trY
Then after resolving you can push your code

**Comment by mundadapurva** [comment]
> #98 Tagging issue number is a must when you are making PR Please take care of this thing next time

Yes, I'll make sure that I mention it next time.

**Comment by mundadapurva** [comment]
> > > Please resolve conflicts
> > 
> > 
> > Could you guide me, please?
> 
> It's easy, You can watch this tutorial https://www.youtube.com/watch?v=nfOxUaA2trY Then after resolving you can push your code

Thanks! I've resolved the conflict now, you can check it once.

**Comment by TusharKesarwani** [comment]
Your code is not perfect
It is changing the UI of a scheduled class section of the website 
Please work upon it
@mundadapurva

**Review by Subhradeep10 — COMMENTED** [review]
PR is closed due to inactivity

**Pull request closed without merging**
