### PR TITLE
I have Added Carousel and Improved UI

### PR DESCRIPTION
**Pull request by Anubhavgupta14**
I have Added Carousel and Improved UI

### CODE REVIEW

**Comment by TusharKesarwani** [comment]
Issue no. #57 
Next time please mention the issue number you are fixing.

**Comment by TusharKesarwani** [comment]
Please paste a screenshot of new UI

**Comment by TusharKesarwani** [comment]
Please paste a screenshot of the new UI you have edited.

**Comment by TusharKesarwani** [comment]
Resolve merge conflicts @Anubhavgupta14

**Comment by Anubhavgupta14** [comment]
Fresh PR has been raised

**Pull request closed without merging**
